name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
change-title-escapes: '\\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking-change'
  minor:
    labels:
      - 'minor'
      - 'enhancement'
      - 'feature'
  patch:
    labels:
      - 'bug'
      - 'fix'
      - 'dependencies'
      - 'translation'
      - 'documentation'
  default: patch

categories:
  - title: '⚠️ Breaking Changes'
    labels:
      - 'major'
      - 'breaking-change'
  - title: '🚀 Features'
    labels:
      - 'enhancement'
      - 'feature'
  - title: '🐛 Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: '🧰 Maintenance'
    labels:
      - 'dependencies'
      - 'ci'
      - 'chore'
  - title: '🌐 Translations'
    labels:
      - 'translation'
  - title: '📚 Documentation'
    labels:
      - 'documentation'

autolabeler:
  - label: 'bug'
    title:
      - '/^fix(\(.+\))?:/i'
    body:
      - '/- \[[xX]\] Bug fix \(non-breaking change which fixes an issue\)/'

  - label: 'enhancement'
    title:
      - '/^(feature|enhancement)(\(.+\))?:/i'
    body:
      - '/- \[[xX]\] New service widget/'
      - '/- \[[xX]\] New feature or enhancement \(non-breaking change which adds functionality\)/'

  - label: 'documentation'
    title:
      - '/^(documentation|docs)(\(.+\))?:/i'
    body:
      - '/- \[[xX]\] Documentation only/'

  - label: 'chore'
    body:
      - '/- \[[xX]\] Other \(please explain\)/'

  - label: 'ci'
    branch:
      - '/^(ci|workflow|actions)\//'
    title:
      - '/^(ci|workflow|actions)(\(.+\))?:/i'

  - label: 'dependencies'
    files:
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pyproject.toml'
      - 'uv.lock'

  - label: 'translation'
    files:
      - 'public/locales/**'

template: |
  ## What's Changed

  $CHANGES
