codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "0...100"
  status:
    project:
      default:
        target: 100%
        threshold: 25%
    patch:
      default:
        target: 100%
        threshold: 25%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
