project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  - source: /public/locales/en/*.json
    translation: /public/locales/%osx_locale%/%original_file_name%
