# =========================
# Development Stage
# =========================
FROM node:22-slim

# Setup
WORKDIR /app

# Install pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

# Copy package files first to leverage Docker cache
COPY package.json pnpm-lock.yaml* ./

# Install dependencies
RUN pnpm install

# Copy the rest of the application code
COPY . .

# Expose the development port
ENV PORT=3000
EXPOSE $PORT

# Start the development server
CMD ["pnpm", "dev"]
 