packages:
  - .

allowBuilds:
  '@tailwindcss/oxide': true
  core-js: false
  cpu-features: false
  esbuild: false
  osx-temperature-sensor: true
  protobufjs: false
  sharp: true
  ssh2: false

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - osx-temperature-sensor
  - protobufjs
  - sharp
