name: Crowdin Action

on:
  workflow_dispatch:
  schedule:
    - cron: '2 */12 * * *'
  push:
    paths: [
      '/public/locales/en/**',
    ]
    branches: [ dev ]

jobs:
  synchronize-with-crowdin:
    name: Crowdin Sync
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - name: crowdin action
      uses: crowdin/github-action@7ca9c452bfe9197d3bb7fa83a4d7e2b0c9ae835d # v2
      with:
        upload_translations: false
        download_translations: true
        crowdin_branch_name: dev
        localization_branch_name: l10n_dev
        pull_request_labels: translation
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
